### ISSUE TITLE
Inventory Profiles Next causes client to crash without new library mod

### ISSUE THREAD

**Issue by LichLord91** [mja00/kami-chan-optimized#1]
https://modrinth.com/mod/inventory-profiles-next  has a new mod library that needs to be installed or else it will crash this current set of mod packs.

New Library mod required https://modrinth.com/mod/libipn

```

[13:16:47] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.util.NoSuchElementException
	at java.util.ArrayDeque.getLast(ArrayDeque.java:413) ~[?:?]
	at net.minecraft.class_4587.method_23760(class_4587.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_48196(class_332.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25294(class_332.java:82) ~[client-intermediary.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58) ~[libIPN-fabric-1.19.4-2.0.4.jar:?]
	at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.5.jar:?]
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source) ~[InventoryProfilesNext-fabric-1.19.4-1.9.5.jar:?]
	at net.minecraft.class_465.handler$bbp000$inventoryprofilesnext$onBackgroundRender(class_465.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:937) ~[client-intermediary.jar:?]
	... 9 more
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.
Time: 2023-04-14 13:16:47
Description: Rendering screen
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_23760(class_4587.java:71)
	at net.minecraft.class_332.method_48196(class_332.java:86)
	at net.minecraft.class_332.method_25294(class_332.java:82)
	at org.anti_ad.mc.common.vanilla.render.glue.DrawableHelperAccess.fillRect(Rect.kt:54)
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:93)
	at org.anti_ad.mc.common.vanilla.render.glue.RectKt.rFillRect(Rect.kt:98)
	at org.anti_ad.mc.common.vanilla.render.GLKt.rOverwriteDepth(GL.kt:109)
	at org.anti_ad.mc.common.vanilla.render.GLKt.rClearDepth(GL.kt:58)
	at org.anti_ad.mc.ipnext.gui.inject.SortingButtonCollectionWidget.postBackgroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onBackgroundRender(Unknown Source)
	at net.minecraft.class_465.handler$bbp000$inventoryprofilesnext$onBackgroundRender(class_465.java)
	at net.minecraft.class_465.method_25394(class_465.java:98)
	at net.minecraft.class_485.method_25394(class_485.java:28)
	at net.minecraft.class_490.method_25394(class_490.java:92)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:937)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by LichLord91** [comment]
Sorry this was incorrect there is a new library as of 1.8.0 but that's not the cause , I crashed again , something is wrong with Inventory Profiles but not a mod pack issue, apologies.

**Comment by mja00** [comment]
I did just update the pack so the crash may be fixed now.
